language: node_js

node_js:
  - "11.0"

branches:
  only:
    - TSSite

cache:
  directories:
    - node_modules

before_script:
  - npm install -g @angular/cli

script:
  - npm install
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/MinecraftProjects
  on:
    branch: TSSite
